### ISSUE TITLE
CMake is not properly formed.

### ISSUE THREAD

**Issue by veljkoveselinovic** [leventesimonplayrix/GroupRPG#2]
CMake will not generate filter structure that corresponds to directory structure.
Also startup project is not set. #1

**Comment by igorkukobat-playrix** [comment]
Added changes in cmake list for set startup project and filters for directory structure.

**Comment by veljkoveselinovic** [comment]
And default cmake projects should be packed together.

**Comment by igorkukobat-playrix** [comment]
Done, now default projects is packed together.
